### ISSUE TITLE
No update rent  in different versions of listing

### ISSUE THREAD

**Issue by AndyManzi** [wpsight/wpcasa-polylang#7]
Hi,
when i change rent in English version, this value isn't update in other version and vice versa

Andy

**Comment by JoeHana** [comment]
Could you describe this issue a little bit more? Where do you try to change this? Basically it is not possible to translate this string with Polylang, so did you change the wording through a filter function? Did you try to translate this string with PO/MO File (like with Loco Translate)?

**Comment by JoeHana** [comment]
Or do you mean that if you change the offer type (rent or sale) in one listing that it doesn't get automatically changed to the translated versions of this listing? If that is the case please check the wpml-config.xml from within the WPCasa Polylang Addon since it included the rules what values should be copied and what should be enabled to translate. By default this is the price_offer which is set to be copied, and this works just fine on our test site.

**Comment by AndyManzi** [comment]
The problem was in the amount of the rent
Problem solved after reinstalling Polylang with the "master" version, which is more
recent than Polylang 2.3.
